FROM influxdb:latest
MAINTAINER Lee YongJin <jjeaby@gmail.com>

# Run upgrades
RUN apt-get update

# Time Zone Setting
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo "Asia/Seoul" > /etc/timezone
 
 # Install basic packages
WORKDIR /opt

# default package install 
RUN apt-get -y install git curl build-essential  libfontconfig vim 


# influxdb install
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs
RUN npm install -U npm
RUN npm install yarn --global

RUN git clone https://github.com/jjeaby/influxdb-ui
WORKDIR /opt/influxdb-ui
RUN yarn install

# grafana install 
# WORKDIR /opt
# RUN wget https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.0.4.linux-x64.tar.gz 
# RUN tar -zxvf grafana-5.0.4.linux-x64.tar.gz 

# RUN wget https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_5.0.4_amd64.deb
# RUN apt-get install -y adduser libfontconfig
# RUN dpkg -i grafana_5.0.4_amd64.deb

RUN echo "deb https://packagecloud.io/grafana/stable/debian/ jessie main" \ 
    >> /etc/apt/sources.list
RUN curl https://packagecloud.io/gpg.key | apt-key add -

RUN apt-get update
RUN apt-get install -f 
RUN apt-get install grafana -y
RUN grafana-cli plugins install michaeldmoore-annunciator-panel
RUN grafana-cli plugins install briangann-gauge-panel

COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
RUN ls


EXPOSE 8083 8086 3000 